#  Site wide configuration

title: Mint Beans
locale: en_US
url: https://mintbeans.com

# Jekyll configuration

permalink: /:categories/:title/
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-gist
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Szymon Jednac
  avatar: avatar1.jpg
  bio: ""
  email: szymon.jednacPLEASEremoveTHISpart@gmail.com
  disqus-shortname: sjednac
  twitter: sjednac
  facebook: #username
  google:
    plus: #username
    analytics: #UA-66813230-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sjednac
  stackoverflow: 1535738/szymon-jednac #123456/username from a "http://stackoverflow.com/users/123456/username" link
  linkedin: sjednac #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude:
  [
    "lib",
    "config.rb",
    "Capfile",
    "config",
    "log",
    "Rakefile",
    "Rakefile.rb",
    "tmp",
    "less",
    "*.sublime-project",
    "*.sublime-workspace",
    "test",
    "spec",
    "Gruntfile.js",
    "package.json",
    "node_modules",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "vendor",
  ]
